version: "3.7"
services:
  database:
    container_name: drupal_database
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    image: mysql:5.7
    volumes:
      - drupal_db:/var/lib/mysql
    ports:
      - "6603:3306"
    expose:
      - "3306"
    networks: 
      - drupal-net
  webapp:
    container_name: web_app
    build:
      context: .
    expose:
      - "9000"
    depends_on:
      - database
    networks: 
      - drupal-net
  nginx:
    container_name: web_server
    image: nginx
    ports:
      - "8008:80"
    expose:
      - "80"
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/web
    depends_on:
      - webapp
    networks: 
      - drupal-net

volumes:
  drupal_db:

networks:
  drupal-net:
