version: "3.7"
services:
  database:
    container_name: drupal_database
    env_file:
      - ./.env
    image: mysql:5.7
    volumes:
      - drupal_db:/var/lib/mysql
    ports:
      - "6603:3306"
    expose:
      - "3306"
  webapp:
    container_name: web_app
    build:
      context: .
    ports: 
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      - database
  nginx:
    container_name: web_server
    image: nginx
    ports:
      - "8008:80"
    volumes:
      - ./configs/nginx/conf.d:/etc/nginx/conf.d
      - ./configs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web:/var/www/web
    depends_on:
      - webapp

volumes:
  drupal_db:
